### PR TITLE
HW6 Part 2 fk2421: Added NPMJs Account and updated proj description

### PR DESCRIPTION
**Pull request by faizak1**

### CODE REVIEW

**Comment by timkpaine** [comment]
need to fix lint

**Comment by faizak1** [comment]
how do we fix the lint issue?

**Comment by timkpaine** [comment]
Screenshot 2023-03-26 at 18 32 04

you can either try to fix them manually (remember to squash!), or since you're a JS person you can use the same tool I use:

```
npm i -g markdownlint
markdownlint --fix projects/javascript/domain-screen-time.md
```

**Comment by faizak1** [comment]
Hi Professor, I tried that but still got this error
Screen Shot 2023-03-26 at 6 39 17 PM

**Comment by faizak1** [comment]
update: this PR is no longer needed.
I have made HW6 part 2 changes in a new PR https://github.com/ColumbiaOSS/project-proposals-s2023/pull/499

**Comment by faizak1** [comment]
update: this PR is no longer needed.
I have made HW6 part 2 changes in a new PR https://github.com/ColumbiaOSS/project-proposals-s2023/pull/499

**Pull request closed without merging**
